name: dominoes
version: 0.9.0.1 # 2016-11-11

dependencies:
  - base

library:
  exposed-modules: Dominoes
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - dominoes
      - hspec
