name: saddle-points

dependencies:
  - array
  - base

library:
  exposed-modules: Matrix
  source-dirs: src
  dependencies:
    - containers
  # - foo       # Here you must list additional packages
  # - bar       # you want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - saddle-points
      - HUnit
