name: parallel-letter-frequency

dependencies:
  - base
  - containers
  - text

library:
  exposed-modules: Frequency
  source-dirs: src
  dependencies:
    - parallel
  # - foo       # Here you must list additional packages
  # - bar       # you want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - parallel-letter-frequency
      - HUnit
