name: sieve

dependencies:
  - base

library:
  exposed-modules: Sieve
  source-dirs: src
  dependencies:
    - vector
  # - foo       # Here you must list additional packages
  # - bar       # you want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - sieve
      - HUnit
