# The Travis docs (https://docs.travis-ci.com/user/languages/haskell)
# suggest that we use `language: haskell` and `ghc:` to specify GHC versions.
# However, as of this writing, Travis only supported versions up to 7.8.
# If Travis supports all versions we would like to test, then we could switch.
# Until then, we use the https://github.com/hvr/multi-ghc-travis setup.
language: c
sudo: false
addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.6.3
      - ghc-7.8.4
      - ghc-7.10.3
      - ghc-8.0.1
      - cabal-install-1.22
env:
  global:
    - CABALVER=1.22
  matrix:
    - GHCVER=7.6.3
    - GHCVER=7.8.4
    - GHCVER=7.10.3
    - GHCVER=8.0.1
cache:
  directories:
    - '$HOME/.ghc'
    - '$HOME/.cabal'
before_install:
  - './_test/bootstrap.sh'
install:
  - true
script:
  - 'export PATH=/opt/cabal/$CABALVER/bin:/opt/ghc/$GHCVER/bin:$PATH'
  - 'runhaskell -Wall ./_test/check-exercises.hs'
  - './bin/fetch-configlet'
  - './bin/configlet .'
