name: palindrome-products

dependencies:
  - base

library:
  exposed-modules: Palindromes
  source-dirs: src
  dependencies:
  # - foo       # Here you must list additional packages
  # - bar       # you want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - palindrome-products
      - containers
      - HUnit
