name: minesweeper
version: 0.9.0.1 # 2016-09-05

dependencies:
  - base

library:
  exposed-modules: Minesweeper
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - minesweeper
      - hspec
