name: ocr-numbers

dependencies:
  - base

library:
  exposed-modules: OCR
  source-dirs: src
  dependencies:
    - containers
    - split
  # - foo       # Here you must list additional packages
  # - bar       # you want to use in you solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - ocr-numbers
      - HUnit
