name: say

dependencies:
  - base

library:
  exposed-modules: Say
  source-dirs: src
  dependencies:
    - array
  # - foo       # Here you must list additional packages
  # - bar       # you want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - say
      - HUnit
