name: raindrops
version: 0.9.0.1 # 2016-09-19

dependencies:
  - base

library:
  exposed-modules: Raindrops
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - raindrops
      - hspec
