name: wordy

dependencies:
  - base

library:
  exposed-modules: WordProblem
  source-dirs: src
  dependencies:
    - attoparsec
    - text
  # - foo       # Here you must list additional packages
  # - bar       # you want to use in you solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - wordy
      - HUnit
