name: binary-search-tree

dependencies:
  - base

library:
  exposed-modules: BST
  source-dirs: src
  dependencies:
  # - foo       # Here you must list additional packages
  # - bar       # you want to use in you solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - binary-search-tree
      - HUnit
