name: connect
version: 0.9.0.1 # 2016-09-16

dependencies:
  - base

library:
  exposed-modules: Connect
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - connect
      - hspec
