name: all-your-base

dependencies:
  - base

library:
  exposed-modules: Base
  source-dirs: src
  dependencies:
  # - foo       # Here you must list additional packages
  # - bar       # you want to use in you solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - all-your-base
      - HUnit
