name: linked-list

dependencies:
  - base

library:
  exposed-modules: Deque
  source-dirs: src
  dependencies:
    - stm
  # - foo       # Here you must list additional packages
  # - bar       # you want to use in you solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - linked-list
      - HUnit
