name: meetup
version: 0.9.0.1 # 2016-07-26

dependencies:
  - base
  - time

library:
  exposed-modules: Meetup
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - meetup
      - hspec
