name: forth

dependencies:
  - base
  - text

library:
  exposed-modules: Forth
  source-dirs: src
  dependencies:
    - containers
  # - foo       # Here you must list additional packages
  # - bar       # you want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - forth
      - HUnit
