name: space-age
version: 0.9.0.1 # 2016-07-27

dependencies:
  - base

library:
  exposed-modules: SpaceAge
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - space-age
      - hspec
