name: anagram

dependencies:
  - base

library:
  exposed-modules: Anagram
  source-dirs: src
  dependencies:
    - containers
    - multiset
    - text

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - anagram
      - hspec
