name: rna-transcription

dependencies:
  - base

library:
  exposed-modules: DNA
  source-dirs: src
  dependencies:
    - containers
  # - foo       # Here you must list additional packages
  # - bar       # you want to use in you solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - rna-transcription
      - HUnit
