name: pov
version: 0.9.0.1 # 2016-11-06

dependencies:
  - base
  - containers

library:
  exposed-modules: POV
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - pov
      - hspec
