name: go-counting

dependencies:
  - base
  - containers

library:
  exposed-modules: Counting
  source-dirs: src
  dependencies:
    - array
  # - foo       # Here you must list additional packages
  # - bar       # you want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - go-counting
      - HUnit
