name: sgf-parsing

dependencies:
  - base
  - containers
  - text

library:
  exposed-modules: Sgf
  source-dirs: src
  dependencies:
    - attoparsec
  # - foo       # Here you must list additional packages
  # - bar       # you want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - sgf-parsing
      - HUnit
