name: queen-attack
version: 0.9.0.1 # 2016-08-02

dependencies:
  - base

library:
  exposed-modules: Queens
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - queen-attack
      - hspec
