name: atbash-cipher

dependencies:
  - base

library:
  exposed-modules: Atbash
  source-dirs: src
  dependencies:
    - split
  # - foo       # Here you must list additional packages
  # - bar       # you want to use in you solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - atbash-cipher
      - HUnit
