name: zipper

dependencies:
  - base

library:
  exposed-modules: Zipper
  source-dirs: src
  dependencies:
  # - foo       # Here you must list additional packages
  # - bar       # you want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - zipper
      - HUnit
