name: etl

dependencies:
  - base
  - containers

library:
  exposed-modules: ETL
  source-dirs: src
  dependencies:
  # - foo       # Here you must list additional packages
  # - bar       # you want to use in you solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - etl
      - HUnit
