name: etl
version: 0.9.0.1 # 2017-01-31

dependencies:
  - base
  - containers

library:
  exposed-modules: ETL
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - etl
      - hspec
