name: matrix

dependencies:
  - base
  - vector

library:
  exposed-modules: Matrix
  source-dirs: src
  dependencies:
  # - foo       # Here you must list additional packages
  # - bar       # you want to use in you solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - matrix
      - HUnit
